draft.pdf :: draft.tex conclusions.tex  draft.tex intro.tex math.tex qudits.tex decoh_set.tex generators.tex  kraus.tex  pce.tex vector_space.tex
notas_JA.pdf :: notas_JA.tex
outline.pdf :: outline.tex

-include ~/makefile
# Repositorio: 
#	url = git@github.com:deleonja/QC.git
