draft.pdf :: draft.tex conclusions.tex  draft.tex intro.tex math.tex qudits.tex decoh_set.tex generators.tex  kraus.tex  pce.tex vector_space.tex proofdiagonalization.tex 2_qubits.tex
notas_JA.pdf :: notas_JA.tex
outline.pdf :: outline.tex

pce.zip :: 
	zip pce.zip 2_qubits.tex decoh_set.tex intro.tex pce.tex quantum_classical.tex a_and_generators.tex draft.tex kraus.tex proofdiagonalization.tex qudits.tex conclusions.tex generators.tex math.tex prueba.tex vector_space.tex images/twoQ_generator_diagrams-crop.pdf references.bib draft.bbl

-include ~/makefile
# Repositorio: 
#	url = git@github.com:deleonja/QC.git
